name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      setupCommand:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.6
  PROJECT_NAME: PsychEngine

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      # Haxe Setup
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      # Java Setup
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Install Lime
      - name: Install Lime
        run: haxelib install lime

      # Install project libraries
      - name: Install Libraries
        run: ${{ inputs.setupCommand }}

      # Android SDK Setup
      - name: Setup Android SDK
        if: inputs.name == 'Android'
        run: |
          sudo mkdir -p /opt/android-sdk
          sudo chown $USER /opt/android-sdk
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip -d /opt/android-sdk
          mv /opt/android-sdk/cmdline-tools /opt/android-sdk/cmdline-tools-temp
          mkdir -p /opt/android-sdk/cmdline-tools/latest
          mv /opt/android-sdk/cmdline-tools-temp/* /opt/android-sdk/cmdline-tools/latest/
          yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "ANDROID_SDK=/opt/android-sdk" >> $GITHUB_ENV

      # Android NDK Setup
      - name: Setup Android NDK
        if: inputs.name == 'Android'
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25b
          add-to-path: false

      # Install linc_luajit
      - name: Install linc_luajit
        if: inputs.name == 'Android'
        run: haxelib install linc_luajit

      # Configure Lime for Android
      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          echo "Configuring Android environment variables"
          haxelib run lime config ANDROID_SDK /opt/android-sdk
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      # Compile
      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      # Upload artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
