name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      assetType:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.7
  PROJECT_NAME: PsychEngine
  ANDROID_PLATFORM: android-33
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install Lime
        run: haxelib install lime

      - name: Install linc_luajit
        run: haxelib install linc_luajit

      - name: Install other Haxe libraries
        run: ${{ inputs.setupCommand }}

      - name: Setup Android SDK
        if: inputs.name == 'Android'
        run: |
          mkdir -p ${{ github.workspace }}/android-sdk
          cd ${{ github.workspace }}/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          yes | ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk --licenses
          ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk "platform-tools" "platforms;${ANDROID_PLATFORM}" "build-tools;33.0.2"
          echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

      - name: Setup Android NDK
        if: inputs.name == 'Android'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b ${{ github.workspace }}/android-ndk
          echo "ANDROID_NDK_ROOT=${{ github.workspace }}/android-ndk" >> $GITHUB_ENV

      - name: Configure Lime for Android
        if: inputs.name == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }} -Dandroid -D ${{ inputs.assetType }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}-${{ inputs.assetType }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
