name: Main

on: workflow_dispatch

jobs:
  Build:
    name: Android
    runs-on: ubuntu-22.04
    uses: ./.github/workflows/build.yml
    with:
      name: Android
      os: ubuntu-22.04
      buildArgs: "android -ONLY_ARMV7"
      setupCommand: sh ./setup/unix.sh
      artifactName: androidBuild
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
