name: Main

on:
  workflow_dispatch:

jobs:
  AndroidBuild:
    uses: ./.github/workflows/build.yml
    with:
      name: Android
      os: ubuntu-22.04
      setupCommand: sh ./setup/unix.sh
      buildArgs: "android -Dandroid -ONLY_ARMV7"
      artifactName: androidBuild
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
